services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./app:/app
      - prism-node-modules:/app/node_modules
    ports:
      - "3000:5173"
    tty: true
    stdin_open: true

volumes:
  prism-node-modules: